services:
  product-service:
    build: ./product-service
    ports:
      - "7002:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  recommendation-service:
    build: ./recommendation-service
    ports:
      - "7003:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  review-service:
    build: ./review-service
    ports:
      - "7004:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  product-composite-service:
    build: ./product-composite-service
    ports:
      - "7001:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
