version: "3.9"

services:

  # -------------------------
  #   MySQL (Review service)
  # -------------------------
  mysql:
    image: mysql:8.0
    container_name: mysql-reviewdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reviewdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -------------------------
  #   MongoDB
  # -------------------------
  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -------------------------
  #   Product-service
  # -------------------------
  product-service:
    build: ./product-service
    ports:
      - "7002:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/product-db
    depends_on:
      mongo:
        condition: service_healthy

  # -------------------------
  #   Recommendation-service
  # -------------------------
  recommendation-service:
    build: ./recommendation-service
    ports:
      - "7003:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/recommendation-db
    depends_on:
      mongo:
        condition: service_healthy

  # -------------------------
  #   Review-service
  # -------------------------
  review-service:
    build: ./review-service
    ports:
      - "7004:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reviewdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy

  # -------------------------
  #   Product Composite
  # -------------------------
  product-composite-service:
    build: ./product-composite-service
    ports:
      - "7001:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      product-service:
        condition: service_started
      recommendation-service:
        condition: service_started
      review-service:
        condition: service_started

# -----------------------------------------
#              VOLUMES
# -----------------------------------------
volumes:
  mysql-data:
  mongo-data:
