spring:
  profiles:
    active: native

---
spring:
  config:
    activate:
      on-profile: native
  mongodb:
    host: localhost
    port: 27017
    database: recommendation-db
server:
  port: 7003

---
spring:
  config:
    activate:
      on-profile: docker
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}
server:
  port: 8080
