spring:
  application:
    name: product-service

---
spring:
  config:
    activate:
      on-profile: native
  mongodb:
    host: localhost
    port: 27017
    database: recommendation-db

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 7002

---
spring:
  config:
    activate:
      on-profile: docker
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

server:
  port: 8080
