spring:
  profiles:
    active: native

---
spring:
  config:
    activate:
      on-profile: native
  mongodb:
    host: localhost
    port: 27017
    database: recommendation-db
server:
  port: 7002

---
spring:
  config:
    activate:
      on-profile: docker
  mongodb:
    host: mongodb
    port: 27017
    database: recommendation-db
server:
  port: 8080
