name: Build & Push Microservice

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Quel microservice builder ?'
        required: true
        default: 'product-service'
        type: choice
        options:
          - product-service
          - recommendation-service
          - review-service
          - product-composite-service
      docker_tag:
        description: 'Tag de l image (défaut: 1.0)'
        required: false
        default: '3.0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # Définit le dossier de travail sur le service choisi
    defaults:
      run:
        working-directory: ./${{ inputs.service_name }}

    steps:
      # 1. Récupération du code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installation du JDK (Version 17 par exemple, à adapter selon tes besoins)
      - name: Set up JDK 17
        uses: actions/setup-java@v5.1.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle' # Cache les dépendances pour aller plus vite

      # 3. Rendre le wrapper Gradle exécutable (par sécurité)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Compilation du JAR sans les tests (-x test)
      - name: Build with Gradle
        run: ./gradlew build -x test

      # 5. Configuration de QEMU/Buildx (nécessaire pour build-push-action)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 6. Connexion au registre Docker (Hub, GHCR, etc.)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Construction de l'image Docker et Push
      # On suppose que le Dockerfile est à la racine du dossier du service
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ inputs.service_name }}
          file: ./${{ inputs.service_name }}/Dockerfile
          push: true
          # Adapte "mon-user" par ton nom d'utilisateur Docker Hub
          tags: ${{ secrets.DUCKER_USERNAME }}/${{ inputs.service_name }}:${{ inputs.docker_tag }}
